### ISSUE TITLE
Miss information about deploy and gh-pages

### ISSUE THREAD

**Issue by JenJenFenFen** [noworneverev/react-vscode-portfolio#2]
hello, my name is Jennyver SL and i used your portfolio project. Your project is cool 👍 

I just want to tell you that you don't make documentation completely about when we want to deploy and post our portfolio via github pages.

I have a problem when I do that. my pages was white and didn't show anything. When I and my friend tried to fix it, we got a solution, and the problem came from package.json, especially at homepage

![image](https://user-images.githubusercontent.com/114470554/214772693-2b19aed1-7d6f-41e3-b658-d09ac52db9df.png)

In your documentation, you didn't tell that we have to change a homepage to our github pages

I have no idea everyone knows about that or not, but i think you should to add this information to your documentation.

I enjoyed for your portfolio project, keep it. Thank you, cheers 👍

**Comment by noworneverev** [comment]
Hi Jennyver,
Thank you for pointing out, I have added more information about deployment in README. You can see that in [7239375](https://github.com/noworneverev/react-vscode-portfolio/commit/7239375b751080e79fb8b3b15179ecf77c244382).
